var inventory = [
        {
            item: 'The Original Phrosty',
            quantity: 100,
            type: alcoholic_drink,
            price: '$12.00',
            description: 'The Phrosty that started it all... and almost ended it all! The Original Phrosty is now officially kind of safe, yet still tastes just as good as ever! Do not drink if you ever plan to travel to a country that requires a yellow fever vaccination or if you ever plan to receive a yellow fever vaccination for any reason.',
            image_url: 'password',
        },
        {
            item: "The I'm Not Getting Involved",
            quantity: 100,
            type: alcoholic_drink,
            price: '$12.00',
            description: 'Shove a straw in your mouth and skip out on the drama! Who needs bad vibes when you can sip your way into banana-coconut bliss.',
            image_url: 'password',
        },
        {
            item: 'The Thank You Berry Much, But No Thanks',
            quantity: 100,
            type: alcoholic_drink,
            price: '$12.00',
            description: 'If something sounds sketchy, then you have to say "No Thanks". Unless, of course, someone is offering you a berry-infused, and berry delicious, Phrosty.',
            image_url: 'password',
        },
        {
            item: "The I'm My Own Date",
            quantity: 100,
            type: alcoholic_drink,
            price: '$12.00',
            description: 'Bring on the dates, cacao nibs, chocolate, and secret ingredient just released in the US. With this Phrosty in hand, you can forget other guys and girls and date yourself!',
            image_url: 'password',
        },
        {
            item: 'The Hair of the Dog',
            quantity: 100,
            type: alcoholic_drink,
            price: '$12.00',
            description: "Now available all day! Yesterday's Phrosty got you feeling under the weather? Suck another one down and you'll be feeling fine in no time. Officially no longer has any hair.",
            image_url: 'password',
        },
        {
            item: "The That's My Bag",
            quantity: 100,
            type: alcoholic_drink,
            price: '$12.00',
            description: "Who cares if it isn't your bag? Who cares if you're making a scene? After this grey-colored dream of a Phrosty, you deserve any damn bag you want! Made with pears and (pretty) edible stones.",
            image_url: 'password',
        },
    ];